Adding L1PFCompare for jet tagging
nhanvtran/FastPUPPI pull request #63
Opened 2023-05-17 21:47 UTC by ddiaz006

Adding @drankincms `L1PFCompare` ntuple for jet tagging studies

@violatingcp @drankincms @jmduarte

2023-05-18 09:22 UTC, gpetruc requested changes
Why you need dictionaries if you're not writing anything into the EDM event?

2023-05-18 09:22 UTC, gpetruc commented on NtupleProducer/README.md
> +git clone git@github.com:ddiaz006/FastPUPPI.git -b 12_5_X
no

2023-05-19 20:31 UTC, ddiaz006 commented
I could be wrong because I am just updating Dylan's original version of this ntupler from 11_1_X, but I think it was added to perform the extended tracking, along with editing this file. https://github.com/p2l1pfp/cmssw/blob/L1PF_12_5_X/L1Trigger/Phase2L1ParticleFlow/plugins/PFTrackProducerFromL1Tracks.cc
Now there is an extended track collection, so it is no longer needed to do that by hand, but I thought we could keep in case we wanted to compare our old results from when there were no extended track collection.

2023-06-07 08:13 UTC, gpetruc commented on NtupleProducer/python/runL1PFNTupler_Full125x.py
> +##process.l1tPFTracksFromL1Tracks.nParam = 5
since they're not needed anymore I think it would be better to remove them entirely and avoid future confusion

2023-06-07 08:13 UTC, gpetruc commented on NtupleProducer/python/runL1PFNTupler_Full125x.py
> +###process.PFInputsTask = cms.Task(
can you remove all this extra unnecessary commented out part

2023-06-07 08:18 UTC, gpetruc approved these changes

2023-06-07 08:18 UTC, gpetruc commented
> Why you need dictionaries if you're not writing anything into the EDM event?

At a second read, I guess you want the dictionaries because you're writing out objects in the TTree ntuple and not just plain arrays.
It's not the cleanest code ever, but eventually the bar on code aesthetics in this repository is lower than for CMSSW so we can have it.

2023-06-08 12:39 UTC, gpetruc commented on NtupleProducer/python/runL1PFNTupler_Full125x.py
> +##process.l1tPFTracksFromL1Tracks.nParam = 5
kept them for now

2023-06-08 12:39 UTC, merged

2023-06-08 13:35 UTC, artlbv commented
Probably to late to ask 😅 but why wasn't the Nano `flattableproducer` used here?

2023-06-09 07:07 UTC, gpetruc commented
I think it's because in their original form all these ntuplizers date back to the pre-nanoAOD era.
But I agree that setting up nanoAOD-based ntuplizers would be better in the future.